# Generated by Django 4.1.13 on 2023-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
